name: Create new Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: "startsWith(github.event.head_commit.message, 'v')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install
        npm install typescript --save-dev

    - name: Read version from manifest
      id: get_version
      run: |
        version=$(jq -r '.header.version | map(tostring) | join(".")' manifest.json)
        echo "Version: $version"
        echo "version=$version" >> $GITHUB_ENV

    - name: Create MCPack
      run: |
        npx ts-node --project tsconfig.json generator/build.ts
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        name: "v${{ env.version }}"
        tag_name: "v${{ env.version }}"
        files: |
          PokeBedrock RES ${{ env.version }}.mcpack
          PokeBedrock RES ${{ env.version }}.zip
        draft: false

    - name: Read CHANGELOG.md
      id: read_changelog
      run: |
        changelog=$(cat CHANGELOG.md | base64)
        echo "$changelog" > changelog_base64.txt
        echo "changelog_path=$(pwd)/changelog_base64.txt" >> $GITHUB_ENV

    - name: Decode CHANGELOG
      id: decode_changelog
      run: |
        changelog=$(cat ${{ env.changelog_path }} | base64 --decode)
        echo "$changelog" > changelog.txt
        echo "decoded_changelog=$(pwd)/changelog.txt" >> $GITHUB_ENV

    - name: Set decoded changelog
      run: |
        echo "DECODED_CHANGELOG=$(cat changelog.txt)" >> $GITHUB_ENV
          
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        avatar-url: "https://cdn.discordapp.com/avatars/1093906253517959248/afcb43ebb982eebca879819dda0ce635.webp"
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        embed-title: "[RES] Update v${{ env.version }}"
        embed-description: "${{ env.DECODED_CHANGELOG }}"
        embed-url: "https://github.com/smell-of-curry/pokebedrock-res"
        filename: "PokeBedrock RES ${{ env.version }}.mcpack"

    - name: Complete Workflow
      run: echo "Workflow completed successfully."
